services:
  - type: web
    name: e-recruitment-backend
    env: docker
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/e-recruitment-0.0.1-SNAPSHOT.jar
    dockerfilePath: Dockerfile
    plan: free
