server:
  servlet:
    context-path: /e-recruitment
  port: 8041

spring:
  application:
    name: e-recruitment
  profiles:
    active: dev
    group:
      dev: h2
      prod: postgres
  jackson:
    serialization:
      fail-on-empty-beans: false
      indent-output: true
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 120MB
      enabled: true

springdoc:
  swagger-ui:
    tags-sorter: alpha

google:
  client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
