package com.bd.erecruitment.enums;

public enum NotificationType {
	APPLICATION_RECEIVED,
	NEW_APPLICATION,
	APPLICATION_STATUS_CHANGED,
	INTERVIEW_SCHEDULED,
	MCQ_TEST_ASSIGNED,
	MCQ_TEST_PASSED,
	MCQ_TEST_FAILED,
	OFFER_RECEIVED,
	OFFER_ACCEPTED,
	OFFER_DECLINED,
	RECRUITER_APPLICATION_SUBMITTED,
	MCQ_RESULT_RECEIVED,
	JOB_ALERT_MATCH,
	INTERVIEW_REMINDER,
	MCQ_TEST_CLOSING,
	JOB_DEADLINE_SOON,
	ONBOARDING_TASK_DUE,
	ADMIN_MESSAGE
}
